/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as BotRouteImport } from './routes/bot'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWhatsappSessionRouteImport } from './routes/api/whatsapp.session'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const BotRoute = BotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappSessionRoute = ApiWhatsappSessionRouteImport.update({
  id: '/api/whatsapp/session',
  path: '/api/whatsapp/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bot': typeof BotRoute
  '/contacts': typeof ContactsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/api/whatsapp/session': typeof ApiWhatsappSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bot': typeof BotRoute
  '/contacts': typeof ContactsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/api/whatsapp/session': typeof ApiWhatsappSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bot': typeof BotRoute
  '/contacts': typeof ContactsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/api/whatsapp/session': typeof ApiWhatsappSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/bot'
    | '/contacts'
    | '/sales'
    | '/settings'
    | '/api/whatsapp/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/bot'
    | '/contacts'
    | '/sales'
    | '/settings'
    | '/api/whatsapp/session'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/bot'
    | '/contacts'
    | '/sales'
    | '/settings'
    | '/api/whatsapp/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BotRoute: typeof BotRoute
  ContactsRoute: typeof ContactsRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRoute
  ApiWhatsappSessionRoute: typeof ApiWhatsappSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot': {
      id: '/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof BotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/session': {
      id: '/api/whatsapp/session'
      path: '/api/whatsapp/session'
      fullPath: '/api/whatsapp/session'
      preLoaderRoute: typeof ApiWhatsappSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BotRoute: BotRoute,
  ContactsRoute: ContactsRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRoute,
  ApiWhatsappSessionRoute: ApiWhatsappSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
